### ISSUE TITLE
Image loading is fucky

### ISSUE THREAD

**Issue by altheaden** [franklindyer/agora-app#65]
Images load slowly (with a significant flash of alt text), and sometimes don't load at all (and only show alt text).

**Comment by altheaden** [comment]
Update: we will probably host images with nginx instead of flask to attempt to better this issue.

**Comment by franklindyer** [comment]
@altheaden As you said this isn't an issue with anything present in this repo. However, I think I've figured out what needs to be done to fix this on the server. We should add the following to the nginx config for our site:
```
location /userimg {
   alias /absolute/path/to/the/images
}
```

**Comment by franklindyer** [comment]
Went ahead and fixed this on the server. Let me know if it's still slow for you - I think it's significantly quicker for me.

**Comment by altheaden** [comment]
Seems to work well for me now, too.
